spring:
  profiles:
    active: test
  main:
    show-banner: false
  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss'Z'
  data:
      mongodb:
        host: localhost
        port: 27017
        database: self

multipart:
  max-file-size: 5MB

server:
  port: 12378
